services:

  service:
    build: 
      args:
        - GITHUB_URL=git@github.com:YOUR_LOGIN/service.git
      context: .
      dockerfile: ./dockerfiles/node-container/Dockerfile
    volumes:
      - "//var/run/docker.sock:/var/run/docker.sock"
    entrypoint:
      - sleep
      - infinity

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    name: pg-data
    external: true